name: Benchmark on PR

on:
  pull_request:
    paths:
      - 'benchmark/**'
      - 'src/**'
      - 'package.json'
      - 'package-lock.json'

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - name: Run benchmarks
        id: bench
        run: |
          OUT="$(node -e 'const fs=require("fs");fs.readdirSync("benchmark").filter(f=>f.endsWith(".mjs")).forEach(f=>{console.log("\n# "+f+"\n");require("child_process").execSync(`node benchmark/${f}`,{stdio:"inherit"})})')"
      - name: Post benchmark results as PR comment
        uses: actions/github-script@v7
        if: github.event_name == 'pull_request'
        with:
          script: |
            const fs = require('fs');
            const { execSync } = require('child_process');
            let output = '';
            fs.readdirSync('benchmark').filter(f => f.endsWith('.mjs')).forEach(f => {
              output += `\n### ${f}\n\n`;
              output += execSync(`node benchmark/${f}`).toString();
            });
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `## Benchmark Results\n${output}`
            }); 